#!/bin/sh
# GENERATED by bin/generate-viewer from apps/signal-desktop.conf + templates/ -- DO NOT EDIT.
# xpra --start-child: set up a passwordless gnome-keyring (Signal stores its DB
# encryption key via libsecret/safeStorage, same pattern as 1Password's 2FA token)
# BEFORE launching Signal. Must run inside dbus-run-session (the entrypoint does that).
set -u
: "${HOME:=/home/signal}"
export HOME

KR="$HOME/.config/Signal/.keyrings"
mkdir -p "$KR" "$HOME/.local/share"
ln -sfn "$KR" "$HOME/.local/share/keyrings" 2>/dev/null || {
  rm -rf "$HOME/.local/share/keyrings"
  ln -sfn "$KR" "$HOME/.local/share/keyrings"
}
if [ ! -e "$KR/default" ]; then
  printf '[keyring]\ndisplay-name=login\nctime=0\nmtime=0\nlock-on-idle=false\nlock-after=false\n' > "$KR/login.keyring"
  chmod 600 "$KR/login.keyring"
  printf login > "$KR/default"
fi
eval "$(printf '' | gnome-keyring-daemon --unlock --components=secrets 2>/dev/null)"

# Launch the app with its manifest-configured flags. (Electron apps typically need
# --no-sandbox here -- their setuid sandbox doesn't work in this container; GTK apps
# usually need none. Set them per-app via APP_FLAGS.)
exec signal-desktop --no-sandbox
